// Demo clock — matches the seeded call data pulled on June 12, 2026.
export const NOW = new Date('2026-06-12T17:30:00+05:30')

export const CLINICS = {
  small: { name: 'Maple Street Vet Clinic', short: 'Maple St.', type: 'Primary care' },
  emergency: { name: 'Northside Emergency & Specialty', short: 'Northside ER', type: '24/7 Emergency' },
}

export const AGENTS = [
  {
    id: '864b0c36-7b52-4f42-9aeb-77445f37b7b2',
    name: 'Priya — Ringg Intake',
    ringgName: 'vetra_RinggMirror',
    clinic: 'small',
    role: 'Production inbound front desk · intake, triage & booking requests',
    number: '+1 (808) 515-8398',
    status: 'live',
    tools: ['greetings', 'lookup_patient', 'check_availability_of_slots', 'book_appointment', 'cancel_appointment', 'reschedule_appointment', 'check_due_care', 'save_call_context', 'notify_emergency_team', 'call_transfer'],
    description:
      'Production Ringg assistant connected to the live dashboard. New inbound calls appear in the Calls queue with transcripts, custom variables, analysis and tool logs.',
  },
  {
    id: '44ab6107-c852-432f-963f-0dc3588f20d4',
    name: 'Priya — Triage',
    ringgName: 'Priya_RinggMirror',
    clinic: 'small',
    role: 'Front desk · intake, triage & booking',
    number: '+1 (208) 470-8994',
    status: 'live',
    tools: ['check_availability_of_slots', 'book_appointment', 'save_call_context'],
    description:
      'Answers every inbound call at the primary clinic. Collects owner, pet and symptom details, scores urgency, books routine and same-day visits on the calendar, and escalates emergencies with full context.',
  },
  {
    id: '67d57938-c98b-453e-a980-13813c24ab0c',
    name: 'Priya — Emergency',
    ringgName: 'Vetra_Recall',
    clinic: 'emergency',
    role: 'Emergency intake · receives warm handoffs',
    number: 'Outbound · triggered on escalation',
    status: 'live',
    tools: ['check_availability_of_slots', 'book_appointment'],
    description:
      'Receives the transferred call with owner name, pet name and reported symptoms already loaded — the owner never repeats themselves. Confirms the case, checks ER availability, and schedules treatment.',
  },
]

// ── Calls ────────────────────────────────────────────────────────────────────
// status: needs_action | unreviewed | reviewed
// urgency: emergency | urgent | routine
// coverage: covered (handled end-to-end) | at_risk (needs human action) | missed (lost)
export const SEED_CALLS = [
  {
    id: '8c1bc359',
    executionId: '8c1bc359-80e0-4e56-aa1b-6b2d0ad201de',
    real: true,
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'urgent',
    coverage: 'at_risk',
    caller: { name: 'Laksharaj', phone: '+91 86968 16868' },
    pet: { name: 'John Wick', species: 'Dog', breed: 'Portuguese Water Dog', age: '4 yrs' },
    reason: 'Vomiting with blood specks',
    summary:
      'Vomiting with blood specks for ~12 hours, severity 6/10. Conscious and responsive; eating and drinking irregular. Priya recommended a same-day visit — call ended before a slot was confirmed.',
    receivedAt: '2026-06-12T16:04:00+05:30',
    duration: 182,
    estValue: 240,
    nextActions: [
      { id: 'a1', label: 'Book same-day urgent visit', type: 'book', done: false },
      { id: 'a2', label: 'Call back to confirm slot', type: 'callback', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from the Pet Healthcare Clinic. Am I speaking with a pet owner today? I’m here to help get your pet the care they need.'],
      ['caller', 'Yes.'],
      ['agent', 'Could you please tell me your name?'],
      ['caller', 'My name is Laksharaj.'],
      ['agent', 'Could you tell me your pet’s name?'],
      ['caller', 'John Wick — W I C K.'],
      ['agent', 'Alright, what kind of pet is it — for example, is it a dog, a cat, or another animal?'],
      ['caller', 'It’s a Portuguese Water Dog.'],
      ['agent', 'Sure, how old is your pet?'],
      ['caller', 'My pet is four years old.'],
      ['agent', 'What seems to be going on with your pet today? Could you describe what you have noticed?'],
      ['caller', 'The pet is vomiting a lot, there are blood specks in the vomit.'],
      ['agent', 'I am sorry to hear that. How long has your pet been showing these signs?'],
      ['caller', 'It’s been twelve hours.'],
      ['agent', 'Understood. On a scale from one to ten, how would you describe the severity — with one being very mild and ten being very serious?'],
      ['caller', 'Maybe six.'],
      ['agent', 'Thank you for sharing that. Is your pet currently conscious and responsive?'],
      ['caller', 'Yeah, my pet is currently conscious and responsive.'],
      ['agent', 'I see. Is your pet breathing normally, eating, or drinking at all?'],
      ['caller', 'Yeah, sort of — sometimes yes, sometimes no.'],
      ['agent', 'Based on what you have described, it sounds like your pet should be seen today. I would like to book a same-day appointment for you. What time today would work best?'],
      ['caller', 'What time today is available?'],
      ['agent', 'Once I complete the intake, I will route you to the appropriate care team who can confirm availability.'],
    ],
  },
  {
    id: 'f90320fc',
    executionId: 'f90320fc-8af7-419e-b571-ef6f18441d36',
    real: true,
    agentId: '67d57938-c98b-453e-a980-13813c24ab0c',
    clinic: 'emergency',
    status: 'reviewed',
    urgency: 'emergency',
    coverage: 'covered',
    handoffFrom: '6a8240e6',
    caller: { name: 'John Desire', phone: '+1 (447) 902-1168' },
    pet: { name: 'Buddy', species: 'Dog', breed: 'Golden Labrador', age: '5 yrs' },
    reason: 'Transferred — leg injury after fall',
    summary:
      'Warm handoff from Maple St. Priya opened with the transferred context — owner, pet and symptom already on file, John confirmed without repeating intake. ER availability checked and visit scheduled.',
    receivedAt: '2026-06-12T03:18:00+05:30',
    duration: 113,
    estValue: 850,
    nextActions: [],
    handoffContext: { owner_name: 'John', pet_name: 'Buddy', reported_symptom: 'Limping, pain in left hind leg' },
    transcript: [
      ['agent', 'Hello, I’m Priya from the Emergency Veterinary Clinic. I have your information from the transfer. Can you confirm your name and your pet’s name so we can help right away?'],
      ['caller', 'It’s John.'],
      ['agent', 'Thank you, John. I understand you have been transferred to us regarding an urgent situation with your pet. Can you please confirm your pet’s name and the issue they are experiencing?'],
      ['caller', 'Yeah, so my pet’s name is Buddy, and Buddy is limping.'],
      ['agent', 'Thank you, John. I have some initial information here that you are reaching out about Buddy with limping. Can you confirm that is correct?'],
      ['caller', 'Yes.'],
      ['agent', 'Before we go any further, how are you holding up right now?'],
      ['caller', 'It’s fine, I’m just looking to book an appointment.'],
      ['agent', 'Got it, thank you. Can you describe what Buddy is doing right now, or what has changed since you first noticed the limping?'],
      ['caller', 'No, I think he’s just feeling pain in his leg, otherwise he’s fine.'],
      ['agent', 'Understood. I am just going to check our current availability for you right now. One moment please.'],
    ],
  },
  {
    id: '6a8240e6',
    executionId: '6a8240e6-096e-4f2d-a7ec-4a290d1b5d50',
    real: true,
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'emergency',
    coverage: 'covered',
    handoffTo: 'f90320fc',
    caller: { name: 'John Desire', phone: '+1 (447) 902-1168' },
    pet: { name: 'Buddy', species: 'Dog', breed: 'Golden Labrador', age: '5 yrs' },
    reason: 'Leg injury — beyond clinic capacity',
    summary:
      'Buddy hurt his leg jumping in the backyard. Triage determined the case needed imaging the clinic couldn’t provide same-night. Caller informed, then transferred to Northside ER with full context.',
    receivedAt: '2026-06-12T03:17:00+05:30',
    duration: 43,
    estValue: 0,
    nextActions: [],
    transcript: [
      ['agent', 'Hello, am I speaking with the pet owner? How can I help you with your pet today?'],
      ['caller', 'Yeah, it’s John. My dog Buddy hurt his leg — he’s in pain and limping badly.'],
      ['agent', 'I’m sorry to hear that. Given the pain and the time of night, Buddy may need imaging we can’t provide right now. I’m going to transfer you to Northside Emergency & Specialty — they’ll already have Buddy’s details, so you won’t have to repeat anything.'],
      ['caller', 'Okay, that works.'],
      ['agent', 'Connecting you now. Stay on the line, John.'],
    ],
  },
  {
    id: 'b04164f2',
    executionId: 'b04164f2-79f1-4950-aecc-07700d663c0c',
    real: true,
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'John Desire', phone: '+1 (447) 902-1168' },
    pet: { name: 'Buddy', species: 'Dog', breed: 'Golden Labrador', age: '5 yrs' },
    reason: 'Follow-up visit booking',
    summary:
      'Returning caller — Priya recognized the number and pulled Buddy’s record from memory. Mild limping follow-up; earliest preferred slot July 3rd morning confirmed and booked on the calendar.',
    receivedAt: '2026-06-12T03:21:00+05:30',
    duration: 301,
    estValue: 95,
    booked: { date: '2026-07-03', time: '09:30', kind: 'Orthopedic re-check' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, am I speaking with the pet owner? How can I help you with your pet today?'],
      ['caller', 'Yeah, it’s John Desire. I have a dog named Buddy, he’s a Golden Labrador and he’s limping.'],
      ['agent', 'Of course, I am happy to help. Could you tell me what is happening with Buddy today?'],
      ['caller', 'As I said, Buddy is limping. He got hurt while jumping around in the backyard. It’s mild — I just want to come and see a doctor. What’s the earliest appointment you guys have?'],
      ['agent', 'Understood. Before I check availability — is he currently experiencing any difficulty breathing, uncontrolled bleeding, seizures, or loss of consciousness?'],
      ['caller', 'No, no. Like I said, it’s just a normal limping.'],
      ['agent', 'I hear you. Would you prefer to come in today, or is there a specific date that works better for you?'],
      ['caller', 'July third works.'],
      ['agent', 'Sure — and what time of day works best for you on the third of July?'],
      ['caller', 'Morning.'],
      ['agent', 'The earliest available slot I can offer you is the third of July at 9:30 AM. Does that work for you?'],
      ['caller', 'Yeah, that works.'],
      ['agent', 'Great, I will book that appointment for Buddy. To complete the booking and send you a confirmation, could I take your full name please?'],
      ['caller', 'It’s John Desire.'],
      ['agent', 'Booked — you’ll get a confirmation by text shortly with directions to the clinic.'],
    ],
  },
  // ── Representative queue (modeled on live pilot data) ──
  {
    id: 'syn-01',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'emergency',
    coverage: 'at_risk',
    caller: { name: 'Meera Shah', phone: '+1 (415) 332-0917' },
    pet: { name: 'Simba', species: 'Cat', breed: 'Maine Coon', age: '7 yrs' },
    reason: 'Collapse — possible urinary blockage',
    summary:
      'Male cat straining in the litter box since morning, now lethargic and cried out when picked up. Classic blockage red flags. Priya flagged emergency and advised immediate ER visit; owner wanted to wait for a callback from the vet first.',
    receivedAt: '2026-06-12T14:42:00+05:30',
    duration: 204,
    estValue: 1400,
    nextActions: [
      { id: 'a1', label: 'Vet callback — confirm ER referral', type: 'callback', done: false },
      { id: 'a2', label: 'Send pre-arrival emergency instructions', type: 'message', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'My cat Simba keeps going to the litter box but nothing comes out. Now he’s just lying there and he screamed when I picked him up.'],
      ['agent', 'I’m sorry — that sounds distressing. For a male cat, straining without producing urine can be an emergency. How long has this been going on?'],
      ['caller', 'Since this morning, maybe eight hours.'],
      ['agent', 'Thank you. Based on what you’re describing, Simba should be seen immediately — this can become life-threatening within hours. I’d like to route you to our emergency partner right away.'],
      ['caller', 'Can the vet call me first? I want to be sure before I drive an hour.'],
      ['agent', 'I understand. I’ve flagged this for an urgent callback — and if Simba gets worse in the meantime, please go straight to Northside Emergency.'],
    ],
  },
  {
    id: 'syn-02',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'urgent',
    coverage: 'at_risk',
    caller: { name: 'Daniel Okafor', phone: '+1 (628) 244-7731' },
    pet: { name: 'Luna', species: 'Dog', breed: 'Beagle', age: '2 yrs' },
    reason: 'Ate chocolate — quantity unclear',
    summary:
      'Luna got into a box of dark chocolate ~1 hour ago. Owner unsure of amount. Priya collected weight (22 lbs) and product details; toxicity calc needs vet sign-off before inducing protocol.',
    receivedAt: '2026-06-12T12:08:00+05:30',
    duration: 156,
    estValue: 310,
    nextActions: [
      { id: 'a1', label: 'Vet review toxicity assessment', type: 'review', done: false },
      { id: 'a2', label: 'Book same-day visit if indicated', type: 'book', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'My beagle Luna just ate some dark chocolate — I don’t know how much, the box is shredded.'],
      ['agent', 'Okay, let’s work through this quickly. How much does Luna weigh, roughly?'],
      ['caller', 'About 22 pounds.'],
      ['agent', 'And was it dark, milk, or baking chocolate?'],
      ['caller', 'Dark, 70 percent I think.'],
      ['agent', 'Thank you. Dark chocolate at that weight can be serious depending on the amount. I’m logging this for an immediate vet review — keep Luna where you can watch her, and don’t feed her anything. We’ll call you back within the next few minutes.'],
    ],
  },
  {
    id: 'syn-03',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'unreviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Priya Nair', phone: '+1 (415) 887-2204' },
    pet: { name: 'Mochi', species: 'Cat', breed: 'Domestic Shorthair', age: '1 yr' },
    reason: 'Vaccination booking',
    summary:
      'Annual FVRCP booster due. Priya checked the calendar, offered three slots, booked Monday 10:00 AM. Confirmation and reminder sequence queued automatically.',
    receivedAt: '2026-06-12T11:21:00+05:30',
    duration: 88,
    estValue: 78,
    booked: { date: '2026-06-15', time: '10:00', kind: 'FVRCP booster' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Hi, I got a reminder that Mochi’s booster is due. Can I book something next week?'],
      ['agent', 'Of course. I have Monday at 10:00 AM, Tuesday at 2:30 PM, or Wednesday at 9:00 AM.'],
      ['caller', 'Monday at 10 works.'],
      ['agent', 'Booked — Mochi, FVRCP booster, Monday June 15th at 10:00 AM. You’ll get a text confirmation now and a reminder the day before.'],
    ],
  },
  {
    id: 'syn-04',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'routine',
    coverage: 'at_risk',
    caller: { name: 'Tom Whitfield', phone: '+1 (510) 663-9012' },
    pet: { name: 'Biscuit', species: 'Dog', breed: 'Corgi', age: '9 yrs' },
    reason: 'Post-surgery check — incision redness',
    summary:
      'Day 5 after dental extraction. Owner reports mild redness at the gumline and reduced appetite. Photos requested via text; vet should review before the scheduled recheck.',
    receivedAt: '2026-06-12T10:02:00+05:30',
    duration: 134,
    estValue: 0,
    nextActions: [
      { id: 'a1', label: 'Review incision photos', type: 'review', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Hi, Biscuit had teeth out last week. The gum looks a bit red and he’s not finishing his food.'],
      ['agent', 'Thanks for flagging it. Mild redness can be normal at day five, but I’d like the vet to take a look. I’m texting you a link now — could you reply with two photos of the gumline?'],
      ['caller', 'Sure, I can do that.'],
      ['agent', 'Perfect. The vet will review them today, and if anything looks off we’ll move your recheck up. Keep him on soft food until then.'],
    ],
  },
  {
    id: 'syn-05',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'unreviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Ana Reyes', phone: '+1 (650) 224-8810' },
    pet: { name: 'Pepper', species: 'Dog', breed: 'Mini Schnauzer', age: '6 yrs' },
    reason: 'Prescription refill',
    summary:
      'Apoquel refill request. Last exam within 12 months, refill eligible. Queued for pharmacist approval; pickup window texted to owner.',
    receivedAt: '2026-06-12T09:36:00+05:30',
    duration: 64,
    estValue: 56,
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'I need a refill on Pepper’s allergy medication, the Apoquel.'],
      ['agent', 'Let me check — Pepper, Mini Schnauzer, last seen in March. You’re eligible for a refill. I’ve queued it for approval; you’ll get a text when it’s ready for pickup, usually within two hours.'],
      ['caller', 'Great, thank you.'],
    ],
  },
  {
    id: 'syn-06',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'urgent',
    coverage: 'missed',
    caller: { name: 'Unknown caller', phone: '+1 (415) 990-3321' },
    pet: { name: '—', species: '—', breed: '', age: '' },
    reason: 'Hang-up before intake',
    summary:
      'Caller disconnected 9 seconds in, before any details were collected. Two callback attempts went to voicemail. Logged as missed revenue.',
    receivedAt: '2026-06-11T22:14:00+05:30',
    duration: 9,
    estValue: 180,
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', '(call disconnected)'],
    ],
  },
  {
    id: 'syn-07',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Grace Lin', phone: '+1 (408) 772-5566' },
    pet: { name: 'Noodle', species: 'Cat', breed: 'Ragdoll', age: '3 yrs' },
    reason: 'After-hours appetite question',
    summary:
      '2:40 AM call. Noodle skipped two meals but is drinking and alert. No red flags on triage; same-day morning slot booked instead of an unnecessary ER trip.',
    receivedAt: '2026-06-12T02:40:00+05:30',
    duration: 142,
    estValue: 95,
    booked: { date: '2026-06-12', time: '11:30', kind: 'Sick visit — inappetence' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Sorry to call so late — Noodle hasn’t eaten since yesterday morning and I’m worried.'],
      ['agent', 'You did the right thing calling. Is Noodle drinking water, and is she alert and moving around normally?'],
      ['caller', 'Yes, she’s drinking and she came to the door just now.'],
      ['agent', 'Good signs. Any vomiting, diarrhea, or hiding behavior?'],
      ['caller', 'No, none of that.'],
      ['agent', 'Then this can safely wait a few hours — no need for an ER visit tonight. I’m booking Noodle into our first sick-visit slot at 11:30 this morning. If anything changes before then, call back and I’ll route you to emergency.'],
    ],
  },
  {
    id: 'syn-08',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'unreviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Hannah Brooks', phone: '+1 (415) 778-4420' },
    pet: { name: 'Waffles', species: 'Dog', breed: 'French Bulldog', age: '3 yrs' },
    reason: 'Dental cleaning booking',
    summary:
      'Routine dental cleaning request. Priya offered availability and booked Friday 1:00 PM. Pre-anesthetic bloodwork note flagged for the clinical team; confirmation and prep instructions queued.',
    receivedAt: '2026-06-12T13:48:00+05:30',
    duration: 97,
    estValue: 320,
    booked: { date: '2026-06-12', time: '13:00', kind: 'Dental cleaning' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Hi, I’d like to get Waffles in for a dental cleaning.'],
      ['agent', 'Happy to help. I can offer this Friday at 1:00 PM or Monday at 3:30 PM.'],
      ['caller', 'Friday at one works.'],
      ['agent', 'Booked — Waffles, dental cleaning, Friday at 1:00 PM. Since dentals use light anesthesia, please keep him fasted from midnight. I’ll text the full prep instructions now.'],
    ],
  },
  {
    id: 'syn-09',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'urgent',
    coverage: 'at_risk',
    caller: { name: 'Marcus Lee', phone: '+1 (628) 551-3094' },
    pet: { name: 'Tofu', species: 'Cat', breed: 'British Shorthair', age: '5 yrs' },
    reason: 'Repeated vomiting, lethargic',
    summary:
      'Cat vomited 4× since last night and is hiding/lethargic. No known toxin exposure. Priya advised a same-day exam; owner asked to check with partner before booking. Callback flagged.',
    receivedAt: '2026-06-12T15:26:00+05:30',
    duration: 171,
    estValue: 260,
    nextActions: [
      { id: 'a1', label: 'Call back to confirm same-day exam', type: 'callback', done: false },
      { id: 'a2', label: 'Hold afternoon slot for 30 min', type: 'book', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'My cat Tofu has thrown up four times since last night and he’s just hiding under the bed.'],
      ['agent', 'I’m sorry to hear that. Any chance he got into plants, string, or anything unusual?'],
      ['caller', 'Not that I know of.'],
      ['agent', 'Repeated vomiting with lethargy is worth a same-day look. I can hold a 4:00 PM slot for you today — would you like me to book it?'],
      ['caller', 'Let me check with my wife and call back in ten minutes.'],
      ['agent', 'Of course. I’ll hold that slot for thirty minutes and flag this for a callback so we don’t lose your place.'],
    ],
  },
  {
    id: 'syn-10',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'unreviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Sofia Martins', phone: '+1 (650) 901-7745' },
    pet: { name: 'Pixel', species: 'Dog', breed: 'Pomeranian', age: '12 wks' },
    reason: 'Puppy first vaccination',
    summary:
      'New puppy, first DHPP visit. Priya collected age and weight, booked the puppy-wellness package for Saturday morning, and queued the vaccination-series schedule for the owner.',
    receivedAt: '2026-06-12T10:41:00+05:30',
    duration: 119,
    estValue: 140,
    booked: { date: '2026-06-13', time: '09:30', kind: 'Puppy wellness + DHPP' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'We just got a puppy, Pixel — she needs her first shots.'],
      ['agent', 'Congratulations! How old is Pixel?'],
      ['caller', 'About twelve weeks.'],
      ['agent', 'Perfect timing for her first DHPP. I have Saturday at 9:30 AM for a puppy-wellness visit — shall I book that?'],
      ['caller', 'Yes please.'],
      ['agent', 'Done. I’ll text you the full puppy vaccination schedule so you know what’s coming over the next few months.'],
    ],
  },
  {
    id: 'syn-11',
    agentId: '67d57938-c98b-453e-a980-13813c24ab0c',
    clinic: 'emergency',
    status: 'needs_action',
    urgency: 'emergency',
    coverage: 'at_risk',
    caller: { name: 'Derek Vaughn', phone: '+1 (415) 220-6658' },
    pet: { name: 'Ranger', species: 'Dog', breed: 'German Shepherd', age: '4 yrs' },
    reason: 'Hit by car — visible distress',
    summary:
      'Dog clipped by a car minutes ago, holding up a front leg and panting heavily. Priya gave transport-stabilization guidance and routed to Northside ER; awaiting ER intake confirmation.',
    receivedAt: '2026-06-12T16:51:00+05:30',
    duration: 88,
    estValue: 1200,
    nextActions: [
      { id: 'a1', label: 'Confirm ER intake received the case', type: 'callback', done: false },
      { id: 'a2', label: 'Send Northside ER directions', type: 'message', done: false },
    ],
    transcript: [
      ['agent', 'Emergency line, this is Priya. Tell me what’s happening with your pet.'],
      ['caller', 'My dog Ranger just got clipped by a car — he’s holding his front leg up and breathing really fast.'],
      ['agent', 'Okay, stay with me. Is he able to stand, and is there any heavy bleeding?'],
      ['caller', 'He’s standing on three legs, no big bleeding that I can see.'],
      ['agent', 'Good. Support him with a blanket as a stretcher if you can, keep him calm, and head to Northside Emergency now — I’m sending the address and letting them know you’re on the way.'],
    ],
  },
  {
    id: 'syn-12',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Elena Popova', phone: '+1 (408) 339-1182' },
    pet: { name: 'Mango', species: 'Cat', breed: 'Siamese', age: '8 yrs' },
    reason: 'Senior wellness + bloodwork',
    summary:
      'Annual senior check-up with geriatric blood panel. Priya booked Thursday morning and noted the owner’s question about weight loss for the vet to address at the visit.',
    receivedAt: '2026-06-11T15:12:00+05:30',
    duration: 126,
    estValue: 185,
    booked: { date: '2026-06-11', time: '11:00', kind: 'Senior wellness + bloodwork' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Mango is eight now — I think she’s due for a senior check, and she seems a little thinner.'],
      ['agent', 'Good idea to get her in. I’d recommend the senior wellness visit with a blood panel. I have Thursday at 11:00 AM.'],
      ['caller', 'That works.'],
      ['agent', 'Booked. I’ve made a note about the weight change so the vet reviews it specifically. Confirmation is on its way.'],
    ],
  },
  {
    id: 'syn-13',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'routine',
    coverage: 'missed',
    caller: { name: 'Unknown caller', phone: '+1 (202) 555-0173' },
    pet: { name: '—', species: '—', breed: '', age: '' },
    reason: 'Wrong number',
    summary:
      'Caller was trying to reach a human dental office, not a vet. Priya clarified, apologized, and ended the call politely. No action needed.',
    receivedAt: '2026-06-11T16:38:00+05:30',
    duration: 21,
    estValue: 0,
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Wait — is this the dentist on 5th Street?'],
      ['agent', 'This is Maple Street Vet Clinic, for pets. It sounds like you may have the wrong number, but I hope you reach the right office soon!'],
    ],
  },
  {
    id: 'syn-14',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'urgent',
    coverage: 'covered',
    caller: { name: 'Raj Malhotra', phone: '+1 (510) 447-2290' },
    pet: { name: 'Shadow', species: 'Dog', breed: 'Border Collie', age: '11 yrs' },
    reason: 'Sudden limp in senior dog',
    summary:
      'Senior dog reluctant to bear weight on a hind leg since this morning, no trauma reported. No red flags on triage. Priya booked a lameness exam for Wednesday and advised crate rest until then.',
    receivedAt: '2026-06-10T09:54:00+05:30',
    duration: 138,
    estValue: 130,
    booked: { date: '2026-06-10', time: '15:30', kind: 'Lameness exam' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'My older dog Shadow is suddenly limping on a back leg — he won’t really put weight on it.'],
      ['agent', 'Did you see any fall or injury, and is he in obvious pain when resting?'],
      ['caller', 'No fall that I saw, and he’s okay when he’s lying down.'],
      ['agent', 'For a senior dog that’s worth an exam, but it can wait a day or two safely. I’ve booked a lameness exam for Wednesday at 3:30 PM. Keep him on leash walks and rest until then.'],
    ],
  },
  {
    id: 'syn-15',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'unreviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Yuki Tanaka', phone: '+1 (415) 662-0048' },
    pet: { name: 'Sushi', species: 'Cat', breed: 'Scottish Fold', age: '2 yrs' },
    reason: 'Microchip + wellness check',
    summary:
      'New adopter wants a microchip and general wellness check. Priya booked Tuesday next week and noted the shelter paperwork to bring along.',
    receivedAt: '2026-06-12T14:05:00+05:30',
    duration: 92,
    estValue: 110,
    booked: { date: '2026-06-16', time: '11:30', kind: 'Microchip + wellness' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'I just adopted a cat, Sushi, and I’d like to get her microchipped and checked over.'],
      ['agent', 'Wonderful. I have Tuesday next week at 11:30 AM for a microchip and wellness check.'],
      ['caller', 'That’s perfect.'],
      ['agent', 'Booked. Please bring any shelter or adoption paperwork you have — I’ll text you the details now.'],
    ],
  },
  {
    id: 'syn-16',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'needs_action',
    urgency: 'urgent',
    coverage: 'at_risk',
    caller: { name: 'Brian Foster', phone: '+1 (628) 110-7782' },
    pet: { name: 'Rex', species: 'Dog', breed: 'Boxer', age: '6 yrs' },
    reason: 'Swollen eye, squinting',
    summary:
      'Dog’s right eye is swollen, red, and held shut since this afternoon. Possible corneal injury. Priya advised a same-day or next-morning exam; owner needs to arrange transport. Callback flagged.',
    receivedAt: '2026-06-12T15:58:00+05:30',
    duration: 147,
    estValue: 220,
    nextActions: [
      { id: 'a1', label: 'Confirm next-morning eye exam slot', type: 'book', done: false },
      { id: 'a2', label: 'Send eye-protection guidance (no rubbing)', type: 'message', done: false },
    ],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'My dog Rex has one eye all swollen and he keeps squinting and pawing at it.'],
      ['agent', 'Thanks for calling. Eye issues can progress quickly, so this should be seen soon. Is there any visible cut or discharge?'],
      ['caller', 'It’s red and a bit weepy, no obvious cut.'],
      ['agent', 'Understood. Keep him from rubbing or pawing the eye — an Elizabethan collar helps if you have one. I can hold the first morning slot tomorrow; would you like me to lock that in?'],
      ['caller', 'Let me sort out a ride and call you back.'],
      ['agent', 'Of course — I’ll flag this for a callback and hold the slot so you don’t lose it.'],
    ],
  },
  {
    id: 'syn-17',
    agentId: '44ab6107-c852-432f-963f-0dc3588f20d4',
    clinic: 'small',
    status: 'reviewed',
    urgency: 'routine',
    coverage: 'covered',
    caller: { name: 'Diane Whitlock', phone: '+1 (510) 884-2261' },
    pet: { name: 'Gus', species: 'Dog', breed: 'Dachshund', age: '7 yrs' },
    reason: 'Anal gland expression',
    summary:
      'Routine recurring grooming/health request. Priya booked a Thursday afternoon slot and noted the recurring 6-week cadence for the owner.',
    receivedAt: '2026-06-11T13:40:00+05:30',
    duration: 71,
    estValue: 45,
    booked: { date: '2026-06-18', time: '14:00', kind: 'Anal gland expression' },
    nextActions: [],
    transcript: [
      ['agent', 'Hello, this is Priya from Maple Street Vet Clinic. How can I help you and your pet today?'],
      ['caller', 'Gus needs his glands done again — he’s scooting.'],
      ['agent', 'No problem. I have Thursday at 2:00 PM. Shall I book it?'],
      ['caller', 'Yes please.'],
      ['agent', 'Done. These tend to recur every six weeks or so — I can set a reminder for the next one if that helps.'],
    ],
  },
]

// ── Memory layer (seeded demo rows, mirrored by Ringg custom variables) ──────
export const MEMORY_ROWS = [
  {
    phone: '+1 (447) 902-1168', caller: 'John Desire', pet: 'Buddy', species: 'Dog', breed: 'Golden Labrador', age: '5 yrs',
    lastSummary: 'Leg injury after backyard fall. Transferred to Northside ER, then booked orthopedic re-check Jul 3.',
    openFollowups: 'Re-check Jul 3 · 9:30 AM', lastAgent: 'Priya — Emergency', updatedAt: '2026-06-12T03:23:00+05:30',
  },
  {
    phone: '+91 86968 16868', caller: 'Laksharaj', pet: 'John Wick', species: 'Dog', breed: 'Portuguese Water Dog', age: '4 yrs',
    lastSummary: 'Vomiting with blood specks ×12h, severity 6/10. Same-day visit recommended, slot not yet confirmed.',
    openFollowups: 'Confirm same-day slot', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T16:07:00+05:30',
  },
  {
    phone: '+1 (415) 332-0917', caller: 'Meera Shah', pet: 'Simba', species: 'Cat', breed: 'Maine Coon', age: '7 yrs',
    lastSummary: 'Suspected urinary blockage — flagged emergency, owner awaiting vet callback before ER trip.',
    openFollowups: 'URGENT vet callback', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T14:45:00+05:30',
  },
  {
    phone: '+1 (415) 887-2204', caller: 'Priya Nair', pet: 'Mochi', species: 'Cat', breed: 'Domestic Shorthair', age: '1 yr',
    lastSummary: 'FVRCP booster booked Jun 15, 10:00 AM. Confirmation sent via SMS.',
    openFollowups: 'Reminder Jun 14', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T11:23:00+05:30',
  },
  {
    phone: '+1 (510) 663-9012', caller: 'Tom Whitfield', pet: 'Biscuit', species: 'Dog', breed: 'Corgi', age: '9 yrs',
    lastSummary: 'Day-5 post dental extraction. Mild gum redness, reduced appetite. Photos requested for vet review.',
    openFollowups: 'Review photos · soft food advisory sent', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T10:05:00+05:30',
  },
  {
    phone: '+1 (650) 224-8810', caller: 'Ana Reyes', pet: 'Pepper', species: 'Dog', breed: 'Mini Schnauzer', age: '6 yrs',
    lastSummary: 'Apoquel refill approved. Pickup window texted.',
    openFollowups: '—', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T09:40:00+05:30',
  },
  {
    phone: '+1 (408) 772-5566', caller: 'Grace Lin', pet: 'Noodle', species: 'Cat', breed: 'Ragdoll', age: '3 yrs',
    lastSummary: '2:40 AM inappetence triage — no red flags, booked same-day 11:30 sick visit, avoided ER trip.',
    openFollowups: 'Post-visit check-in tonight', lastAgent: 'Priya — Triage', updatedAt: '2026-06-12T02:45:00+05:30',
  },
]

// ── Calendar ────────────────────────────────────────────────────────────────
export const SEED_APPOINTMENTS = [
  { id: 'ap1', date: '2026-06-12', time: '09:00', dur: 30, pet: 'Rocky', owner: 'S. Patel', kind: 'Annual exam', source: 'agent' },
  { id: 'ap2', date: '2026-06-12', time: '10:30', dur: 30, pet: 'Daisy', owner: 'K. Moore', kind: 'Dental cleaning', source: 'staff' },
  { id: 'ap3', date: '2026-06-12', time: '11:30', dur: 30, pet: 'Noodle', owner: 'Grace Lin', kind: 'Sick visit — inappetence', source: 'agent', callId: 'syn-07' },
  { id: 'ap4', date: '2026-06-12', time: '15:00', dur: 30, pet: 'Coco', owner: 'R. Fernandes', kind: 'Vaccination', source: 'agent' },
  { id: 'ap5', date: '2026-06-15', time: '10:00', dur: 30, pet: 'Mochi', owner: 'Priya Nair', kind: 'FVRCP booster', source: 'agent', callId: 'syn-03' },
  { id: 'ap6', date: '2026-06-15', time: '14:30', dur: 30, pet: 'Zeus', owner: 'M. Brown', kind: 'Lameness exam', source: 'staff' },
  { id: 'ap7', date: '2026-06-16', time: '09:30', dur: 30, pet: 'Lily', owner: 'J. Carter', kind: 'Spay consult', source: 'agent' },
  { id: 'ap8', date: '2026-06-13', time: '12:00', dur: 30, pet: 'Max', owner: 'D. Kim', kind: 'Skin allergy', source: 'agent' },
  // ── Earlier in the week ──
  { id: 'ap9', date: '2026-06-08', time: '09:00', dur: 30, pet: 'Bella', owner: 'N. Rossi', kind: 'Annual exam', source: 'staff' },
  { id: 'ap10', date: '2026-06-08', time: '14:00', dur: 30, pet: 'Oscar', owner: 'P. Adeyemi', kind: 'Ear infection recheck', source: 'agent' },
  { id: 'ap11', date: '2026-06-09', time: '10:00', dur: 30, pet: 'Milo', owner: 'C. Tanaka', kind: 'Vaccination', source: 'agent' },
  { id: 'ap12', date: '2026-06-09', time: '15:30', dur: 30, pet: 'Cleo', owner: 'L. Schmidt', kind: 'Spay consult', source: 'staff' },
  { id: 'ap13', date: '2026-06-10', time: '11:00', dur: 30, pet: 'Honey', owner: 'F. Castro', kind: 'Itchy skin / allergy', source: 'agent' },
  { id: 'ap14', date: '2026-06-10', time: '15:30', dur: 30, pet: 'Shadow', owner: 'Raj Malhotra', kind: 'Lameness exam', source: 'agent', callId: 'syn-14' },
  { id: 'ap15', date: '2026-06-11', time: '11:00', dur: 30, pet: 'Mango', owner: 'Elena Popova', kind: 'Senior wellness + bloodwork', source: 'agent', callId: 'syn-12' },
  { id: 'ap16', date: '2026-06-11', time: '16:00', dur: 30, pet: 'Ziggy', owner: 'H. Nguyen', kind: 'Nail trim + glands', source: 'staff' },
  // ── Today (Jun 12) extras ──
  { id: 'ap17', date: '2026-06-12', time: '08:30', dur: 30, pet: 'Pepper', owner: 'A. Reyes', kind: 'Prescription recheck', source: 'agent' },
  { id: 'ap18', date: '2026-06-12', time: '13:00', dur: 30, pet: 'Waffles', owner: 'Hannah Brooks', kind: 'Dental cleaning', source: 'agent', callId: 'syn-08' },
  { id: 'ap19', date: '2026-06-12', time: '16:00', dur: 30, pet: 'Tofu', owner: 'Marcus Lee', kind: 'Sick visit — vomiting', source: 'agent', callId: 'syn-09' },
  // ── Saturday (Jun 13) extras ──
  { id: 'ap20', date: '2026-06-13', time: '09:30', dur: 30, pet: 'Pixel', owner: 'Sofia Martins', kind: 'Puppy wellness + DHPP', source: 'agent', callId: 'syn-10' },
  { id: 'ap21', date: '2026-06-13', time: '14:00', dur: 30, pet: 'Rufus', owner: 'B. O’Connor', kind: 'Weight-loss check-in', source: 'staff' },
  // ── Next week ──
  { id: 'ap22', date: '2026-06-15', time: '09:00', dur: 30, pet: 'Charlie', owner: 'T. Iwu', kind: 'Annual exam', source: 'staff' },
  { id: 'ap23', date: '2026-06-15', time: '15:30', dur: 30, pet: 'Olive', owner: 'M. Delgado', kind: 'Dermatology recheck', source: 'agent' },
  { id: 'ap24', date: '2026-06-16', time: '11:30', dur: 30, pet: 'Sushi', owner: 'Yuki Tanaka', kind: 'Microchip + wellness', source: 'agent', callId: 'syn-15' },
  { id: 'ap25', date: '2026-06-16', time: '13:30', dur: 30, pet: 'Bruno', owner: 'K. Larsson', kind: 'Dental recheck', source: 'staff' },
  { id: 'ap26', date: '2026-06-17', time: '10:00', dur: 30, pet: 'Willow', owner: 'A. Petrov', kind: 'Vaccination', source: 'agent' },
  { id: 'ap27', date: '2026-06-18', time: '14:00', dur: 30, pet: 'Gus', owner: 'Diane Whitlock', kind: 'Anal gland expression', source: 'agent', callId: 'syn-17' },
  // ── Filling out the week ──
  { id: 'ap28', date: '2026-06-08', time: '11:00', dur: 30, pet: 'Teddy', owner: 'J. Almeida', kind: 'Vaccination', source: 'agent' },
  { id: 'ap29', date: '2026-06-08', time: '16:00', dur: 30, pet: 'Nala', owner: 'R. Goldberg', kind: 'Sick visit — cough', source: 'agent' },
  { id: 'ap30', date: '2026-06-09', time: '09:00', dur: 30, pet: 'Pumpkin', owner: 'S. Verma', kind: 'Annual exam', source: 'staff' },
  { id: 'ap31', date: '2026-06-09', time: '13:00', dur: 30, pet: 'Rocco', owner: 'D. Bauer', kind: 'Limp recheck', source: 'agent' },
  { id: 'ap32', date: '2026-06-10', time: '09:30', dur: 30, pet: 'Maple', owner: 'E. Conti', kind: 'Wellness exam', source: 'agent' },
  { id: 'ap33', date: '2026-06-10', time: '13:30', dur: 30, pet: 'Boots', owner: 'F. Mwangi', kind: 'Dental cleaning', source: 'staff' },
  { id: 'ap34', date: '2026-06-11', time: '09:30', dur: 30, pet: 'Cooper', owner: 'L. Romano', kind: 'Vaccination', source: 'agent' },
  { id: 'ap35', date: '2026-06-11', time: '14:00', dur: 30, pet: 'Suki', owner: 'P. Andersen', kind: 'Ear infection', source: 'agent' },
  { id: 'ap36', date: '2026-06-12', time: '12:00', dur: 30, pet: 'Bingo', owner: 'M. Flores', kind: 'Suture removal', source: 'agent' },
  { id: 'ap37', date: '2026-06-12', time: '14:00', dur: 30, pet: 'Hazel', owner: 'C. Park', kind: 'Allergy recheck', source: 'staff' },
  { id: 'ap38', date: '2026-06-13', time: '10:30', dur: 30, pet: 'Duke', owner: 'A. Silva', kind: 'Wellness exam', source: 'agent' },
  { id: 'ap39', date: '2026-06-13', time: '15:30', dur: 30, pet: 'Poppy', owner: 'G. Hughes', kind: 'Nail trim + glands', source: 'staff' },
  // ── More fill: current week gaps ──
  { id: 'ap40', date: '2026-06-08', time: '10:00', dur: 30, pet: 'Archie', owner: 'V. Nguyen', kind: 'Limp recheck', source: 'agent' },
  { id: 'ap41', date: '2026-06-08', time: '13:00', dur: 30, pet: 'Juno', owner: 'T. Becker', kind: 'Skin allergy', source: 'agent' },
  { id: 'ap42', date: '2026-06-09', time: '11:30', dur: 30, pet: 'Leo', owner: 'M. Sato', kind: 'Vaccination', source: 'agent' },
  { id: 'ap43', date: '2026-06-09', time: '16:00', dur: 30, pet: 'Daisy', owner: 'R. Khan', kind: 'Sick visit — diarrhea', source: 'staff' },
  { id: 'ap44', date: '2026-06-10', time: '10:00', dur: 30, pet: 'Biscuit', owner: 'L. Ortiz', kind: 'Suture removal', source: 'agent' },
  { id: 'ap45', date: '2026-06-10', time: '16:30', dur: 30, pet: 'Mocha', owner: 'P. Dubois', kind: 'Wellness exam', source: 'agent' },
  { id: 'ap46', date: '2026-06-11', time: '10:00', dur: 30, pet: 'Toby', owner: 'A. Greco', kind: 'Dental recheck', source: 'agent' },
  { id: 'ap47', date: '2026-06-11', time: '13:00', dur: 30, pet: 'Cleo', owner: 'S. Haddad', kind: 'Vaccination', source: 'agent' },
  { id: 'ap48', date: '2026-06-13', time: '11:00', dur: 30, pet: 'Frankie', owner: 'D. Walsh', kind: 'Sick visit — vomiting', source: 'agent' },
  { id: 'ap49', date: '2026-06-13', time: '13:00', dur: 30, pet: 'Ginger', owner: 'N. Abebe', kind: 'Allergy recheck', source: 'staff' },
  // ── Next week (Jun 15–20) ──
  { id: 'ap50', date: '2026-06-15', time: '11:00', dur: 30, pet: 'Zoe', owner: 'C. Russo', kind: 'Spay consult', source: 'agent' },
  { id: 'ap51', date: '2026-06-15', time: '13:00', dur: 30, pet: 'Bandit', owner: 'F. Ali', kind: 'Dental cleaning', source: 'staff' },
  { id: 'ap52', date: '2026-06-16', time: '09:00', dur: 30, pet: 'Lola', owner: 'M. Costa', kind: 'Annual exam', source: 'agent' },
  { id: 'ap53', date: '2026-06-16', time: '15:00', dur: 30, pet: 'Otis', owner: 'J. Park', kind: 'Vaccination', source: 'agent' },
  { id: 'ap54', date: '2026-06-17', time: '11:30', dur: 30, pet: 'Penny', owner: 'R. Lindqvist', kind: 'Sick visit — ear', source: 'agent' },
  { id: 'ap55', date: '2026-06-17', time: '14:30', dur: 30, pet: 'Bear', owner: 'T. Nakamura', kind: 'Lameness exam', source: 'staff' },
  { id: 'ap56', date: '2026-06-18', time: '09:30', dur: 30, pet: 'Coco', owner: 'A. Fischer', kind: 'Wellness exam', source: 'agent' },
  { id: 'ap57', date: '2026-06-18', time: '11:00', dur: 30, pet: 'Simba', owner: 'Meera Shah', kind: 'Urinary recheck', source: 'agent', callId: 'syn-01' },
  { id: 'ap58', date: '2026-06-19', time: '10:00', dur: 30, pet: 'Ruby', owner: 'G. Moreau', kind: 'Vaccination', source: 'agent' },
  { id: 'ap59', date: '2026-06-19', time: '14:00', dur: 30, pet: 'Hank', owner: 'B. Schulz', kind: 'Dental cleaning', source: 'staff' },
  { id: 'ap60', date: '2026-06-20', time: '10:30', dur: 30, pet: 'Pippa', owner: 'L. Esposito', kind: 'Annual exam', source: 'agent' },
  // ── Following week (Jun 22-27) ──
  { id: 'ap61', date: '2026-06-22', time: '09:00', dur: 30, pet: 'Scout', owner: 'I. Bennett', kind: 'Annual exam', source: 'staff' },
  { id: 'ap62', date: '2026-06-22', time: '10:30', dur: 30, pet: 'Miso', owner: 'A. Chen', kind: 'Kitten vaccines', source: 'agent' },
  { id: 'ap63', date: '2026-06-22', time: '14:00', dur: 30, pet: 'Riley', owner: 'P. Singh', kind: 'Dermatology recheck', source: 'staff' },
  { id: 'ap64', date: '2026-06-23', time: '09:30', dur: 30, pet: 'Theo', owner: 'C. Meyer', kind: 'Dental consult', source: 'agent' },
  { id: 'ap65', date: '2026-06-23', time: '11:00', dur: 30, pet: 'Mabel', owner: 'S. Duarte', kind: 'Senior wellness', source: 'staff' },
  { id: 'ap66', date: '2026-06-23', time: '15:30', dur: 30, pet: 'Finn', owner: 'H. Wallace', kind: 'Ear infection recheck', source: 'agent' },
  { id: 'ap67', date: '2026-06-24', time: '10:00', dur: 30, pet: 'Bruno', owner: 'Maya Shah', kind: 'FVRCP booster review', source: 'agent' },
  { id: 'ap68', date: '2026-06-24', time: '13:00', dur: 30, pet: 'Kiki', owner: 'N. Gupta', kind: 'Wellness exam', source: 'staff' },
  { id: 'ap69', date: '2026-06-24', time: '16:00', dur: 30, pet: 'Taco', owner: 'R. Evans', kind: 'Lameness exam', source: 'agent' },
  { id: 'ap70', date: '2026-06-25', time: '09:00', dur: 30, pet: 'Blue', owner: 'J. Morgan', kind: 'Vaccination', source: 'agent' },
  { id: 'ap71', date: '2026-06-25', time: '11:30', dur: 30, pet: 'Minnie', owner: 'E. Hassan', kind: 'Dental cleaning', source: 'staff' },
  { id: 'ap72', date: '2026-06-25', time: '14:30', dur: 30, pet: 'Bowie', owner: 'T. Rossi', kind: 'Allergy recheck', source: 'agent' },
  { id: 'ap73', date: '2026-06-26', time: '09:30', dur: 30, pet: 'Luna', owner: 'Daniel Okafor', kind: 'Toxin follow-up', source: 'agent' },
  { id: 'ap74', date: '2026-06-26', time: '12:00', dur: 30, pet: 'Sunny', owner: 'B. Kim', kind: 'Microchip + wellness', source: 'staff' },
  { id: 'ap75', date: '2026-06-26', time: '15:00', dur: 30, pet: 'Marley', owner: 'O. Jensen', kind: 'Sick visit - cough', source: 'agent' },
  { id: 'ap76', date: '2026-06-27', time: '09:00', dur: 30, pet: 'Noodle', owner: 'Grace Lin', kind: 'Appetite recheck', source: 'agent' },
  { id: 'ap77', date: '2026-06-27', time: '10:30', dur: 30, pet: 'Otto', owner: 'F. Navarro', kind: 'Puppy wellness', source: 'staff' },
  { id: 'ap78', date: '2026-06-27', time: '13:00', dur: 30, pet: 'Clover', owner: 'M. Wilson', kind: 'Nail trim + glands', source: 'agent' },
]

// ── Follow-up sequences ─────────────────────────────────────────────────────
export const SEED_FOLLOWUPS = [
  {
    id: 'fu1', petOwner: 'John Desire · Buddy', callId: 'f90320fc',
    steps: [
      { channel: 'SMS', label: 'ER transfer confirmation + Northside address & directions', at: '2026-06-12T03:25:00+05:30', status: 'sent' },
      { channel: 'WhatsApp', label: 'Pre-arrival instructions — keep weight off the leg, bring vaccine records', at: '2026-06-12T03:26:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Re-check confirmation — Jul 3, 9:30 AM, Maple St.', at: '2026-06-12T03:55:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'Visit summary + discharge notes', at: '2026-06-12T08:00:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Day-3 recovery check-in', at: '2026-06-15T10:00:00+05:30', status: 'scheduled' },
      { channel: 'SMS', label: 'Re-check reminder (24h before)', at: '2026-07-02T09:30:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu2', petOwner: 'Priya Nair · Mochi', callId: 'syn-03',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 15, 10:00 AM', at: '2026-06-12T11:23:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'New-patient forms + parking details', at: '2026-06-12T11:24:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Reminder (24h before)', at: '2026-06-14T10:00:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu3', petOwner: 'Grace Lin · Noodle', callId: 'syn-07',
    steps: [
      { channel: 'SMS', label: 'Same-day booking confirmation — 11:30 AM', at: '2026-06-12T02:46:00+05:30', status: 'sent' },
      { channel: 'WhatsApp', label: 'What to bring + fasting guidance', at: '2026-06-12T07:30:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Post-visit check-in', at: '2026-06-12T19:00:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu4', petOwner: 'Tom Whitfield · Biscuit', callId: 'syn-04',
    steps: [
      { channel: 'SMS', label: 'Photo upload link for incision check', at: '2026-06-12T10:04:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Soft-food care instructions', at: '2026-06-12T10:05:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Vet review result + next steps', at: '2026-06-12T18:00:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu5', petOwner: 'Hannah Brooks · Waffles', callId: 'syn-08',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 12, 1:00 PM', at: '2026-06-12T13:50:00+05:30', status: 'sent' },
      { channel: 'WhatsApp', label: 'Pre-anesthetic fasting instructions (from midnight)', at: '2026-06-12T13:51:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'Dental consent form + estimate', at: '2026-06-12T13:52:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Post-dental soft-food + recovery check-in', at: '2026-06-13T17:00:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu6', petOwner: 'Sofia Martins · Pixel', callId: 'syn-10',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 13, 9:30 AM', at: '2026-06-12T10:43:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'Puppy vaccination schedule (DHPP series)', at: '2026-06-12T10:44:00+05:30', status: 'sent' },
      { channel: 'WhatsApp', label: 'New-puppy welcome pack + what to bring', at: '2026-06-12T10:45:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Reminder (24h before)', at: '2026-06-12T09:30:00+05:30', status: 'scheduled' },
      { channel: 'SMS', label: 'Booster due reminder (3 weeks)', at: '2026-07-04T09:30:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu7', petOwner: 'Marcus Lee · Tofu', callId: 'syn-09',
    steps: [
      { channel: 'SMS', label: 'Held slot reminder — 4:00 PM today, reply to confirm', at: '2026-06-12T15:28:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'What to monitor before the visit (vomiting frequency)', at: '2026-06-12T15:29:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Callback if unconfirmed in 30 min', at: '2026-06-12T15:58:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu8', petOwner: 'Elena Popova · Mango', callId: 'syn-12',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 11, 11:00 AM', at: '2026-06-11T15:14:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'Senior wellness panel — fasting guidance', at: '2026-06-11T15:15:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'Bloodwork results + vet notes', at: '2026-06-11T16:30:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Weight-tracking check-in (2 weeks)', at: '2026-06-25T10:00:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu9', petOwner: 'Yuki Tanaka · Sushi', callId: 'syn-15',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 16, 11:30 AM', at: '2026-06-12T14:07:00+05:30', status: 'sent' },
      { channel: 'Email', label: 'New-patient + microchip registration form', at: '2026-06-12T14:08:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Bring adoption/shelter paperwork', at: '2026-06-12T14:09:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Reminder (24h before)', at: '2026-06-15T11:30:00+05:30', status: 'scheduled' },
    ],
  },
  {
    id: 'fu10', petOwner: 'Diane Whitlock · Gus', callId: 'syn-17',
    steps: [
      { channel: 'SMS', label: 'Booking confirmation — Jun 18, 2:00 PM', at: '2026-06-11T13:42:00+05:30', status: 'sent' },
      { channel: 'SMS', label: 'Reminder (24h before)', at: '2026-06-17T14:00:00+05:30', status: 'scheduled' },
      { channel: 'SMS', label: 'Next-cycle reminder (6 weeks)', at: '2026-07-30T10:00:00+05:30', status: 'scheduled' },
    ],
  },
]

export const fmtMoney = (n) => '$' + n.toLocaleString('en-US')

export const fmtTime = (iso) => {
  const d = new Date(iso)
  return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
}

export const fmtDay = (iso) => {
  const d = new Date(iso)
  const today = NOW.toDateString() === d.toDateString()
  return today ? 'Today' : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

export const fmtDur = (s) => (s >= 60 ? `${Math.floor(s / 60)}m ${s % 60}s` : `${s}s`)
